### ISSUE TITLE
How to gracefully update backend without affecting online users?

### ISSUE THREAD

**Issue by shujaatak** [freehackquest/fhq-server#131]
Wouldn't updating the backend will disconnect all users and affecting the users which are online? I just curious if I use this backend and if someone post some useful/critical data while I update the backend that data will be missed OR am I missing something to understand?

**Comment by sea-kg** [comment]
Which backend are you using now?

**Comment by shujaatak** [comment]
I am not using yet but before using I have got some questions in my mind.

**Comment by sea-kg** [comment]
Client web application must control connection to server.
And if server will be not available sometime... client can try reconnect several times.
Also all data keep on client side before send to server and forget after confirm by server about it received.

So.... data will miss only in one case: If client will be not send again it.
