### ISSUE TITLE
Static analizing text

### ISSUE THREAD

**Issue by sea-kg** [freehackquest/fhq-server#33]
Create in Utils:

QMap<QChar, double> UtilStaticAnalizeText(const QString &text);

Also unit tests please

**Comment by IgorPolyakov** [comment]
The implemented method must be static

**Comment by IgorPolyakov** [comment]
Есть вопрос.
Что дожно быть на выходе.
Посчитать колличество букв? Или посчитать в процентном соотношении?

Еще вопрос. При написании теста, как сравнить на QMap'а
Я так понял QMap == QMap не работатет..

**Comment by sea-kg** [comment]
1. В процентном соотношении.
2. используй std )))
